language: android
android:
  components:
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
addons:
  sonarcloud:
    organization: "markusfisch-github"
    token:
      secure: "sTcztxyA9C6CDCUxdWYnMiEfSD+UgouBTTW8hjWg1JPUTjXQoZC3sy55+2JHjZpBA5bpMloePZ7C8nYzOIn2SB4iNqAl//2pVLg3q7iuYosp7d/bakpTJBbQcjdig4P+8Mn3+YqAxxXf+9wyotcKP3yVSSDzFbC4jllUEdwNqdLbtL+nGSivuAhmfqBUWyynhexM73WdR0Ks2jJr+JEhemSfaOCerLFfBA8T/37ihcPFZjrpaZ/S8ptro9RpK0bZXr+2oIG/iNkT3dreGJlNrAUlIRw5ggBI+F8p012Bi5tqIUVtrnhcw2rAFL70DjkumaWS+4/rjE9eNN4dQXhGmfJk2e21VhaWMa+Cxn+E04KY5sVq446ltH38OjCDdzTL9EZPslLaJ3H9B4uKasUITKJO49aWWfuhW9y1QXp2P2X8LtyKSh2+nVtwUXoaKt4/0iU9Y19pQ3eIP+XN9kedwNPijN+DUvkYi6/FGC550fAPzFS+VRqCMuJzT2Gc3w/Gn5A3nM7RAq5AniyottaYkIi/lbnvoZpLQH+P+yY+dLVs0YLiqzmu2Yk1NAHFPnwH3HYzZbixaTHQ6BcSJ2PXGJJrseq/XjRP7oLjw4pyaWwy1xxxSs1Tgc5G1vtN8kUu43exxs/rKAccrEsu5IHYCWnEzXY9xhwdVIramBzoFUg="
script:
  - bash gradlew build
  - bash gradlew sonarqube
branches:
  only:
    - master
